@startuml

title Eksempel-diagram
footer Undertekst A

class Folk {
    -Navn : string
    +Fødselsår : int
}
class Sykkel
class Tastatur
class Datamaskin {
    +Svenskeknapp : boolean
} 

Folk <-- Datamaskin
Folk <-- Sykkel
Tastatur --o Datamaskin

@enduml